// <auto-generated />
using BACK.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BACK.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230218104035_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("BACK.Models.Categories", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("BACK.Models.Subcategories", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("categoriesid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("categoriesid");

                    b.ToTable("subcategories");
                });

            modelBuilder.Entity("BACK.Models.Topics", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("subcategoriesid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("subcategoriesid");

                    b.ToTable("topics");
                });

            modelBuilder.Entity("BACK.Models.Subcategories", b =>
                {
                    b.HasOne("BACK.Models.Categories", "Categories")
                        .WithMany()
                        .HasForeignKey("categoriesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("BACK.Models.Topics", b =>
                {
                    b.HasOne("BACK.Models.Subcategories", "Subcategories")
                        .WithMany()
                        .HasForeignKey("subcategoriesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subcategories");
                });
#pragma warning restore 612, 618
        }
    }
}
